### ISSUE TITLE
Support authentication with Workload Identity

### ISSUE THREAD

**Issue by danigian** [Azure/aad-auth-proxy#38]
Due to a legacy version of the azidentity sdk, this project is not supporting the use of Workload Identity authentication.

It would be great to add the support for such authentication option, to enable secretless scenarios and increased manageability and security.

At the moment, a simple workaround might be to just update the azidentity sdk to latest version.
In general, why not relying on [default environment variables](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#readme-environment-variables) and let azidentity sdk manage the complexity of the different ways to authenticate against Entra ID?

**Comment by danigian** [comment]
Thanks for the answer, it's not (yet) a hard requirement. Honestly looking forward to seeing it implemented in the future 👍

**Comment by mablouin** [comment]
I am also interested in having support for workload identities. This proxy is currently the only way to get authentication with the OpenTelemetry collectors and I would very much prefer to use workload identities for this, like all the other identities in my clusters.

I agree with danigian that it would probably be better to have support for the DefaultAzureCredential and use environment variables to configure the identities.

**Comment by nasundar** [comment]
Apologies for delayed response, was on vacation came back today.

We will add support for workload identity in Jan 2024. Support for DefaultAzureCredential will likely come out in a separate release after workload identity.

@danigian @mablouin would it still be useful in your scenarios if we stagger releases for workload identity and DefaultAzureCredential? or would you want to wait and have both workload identity and DefaultAzureCredential together? Please let me know, this will help us in prioritizing releases.

**Comment by mablouin** [comment]
@nasundar Sorry for late reply. Yes, support for workload identities without DefaultAzureCredential is good enough. I just felt like going forward, supporting DefaultAzureCredential provides the easiest maintenance for new types of credentials, regardless of what Microsoft is cooking.

**Comment by nasundar** [comment]
@mablouin : Thanks for confirming and makes sense. I will update the thread when we have added support, I will work on it this month.

**Comment by mschmidt291** [comment]
Hi @nasundar Any updated on the status of using Workload Identity for the proxy?

**Comment by nasundar** [comment]
@mschmidt291: I have completed changes; I am testing a few scenarios. I will release tomorrow including both - workloadIdentity + DefaultAzureCredential, along with docs.
